font_family      JetBrainsMono Nerd Font
font_size        12.0
disable_ligatures never

modify_font underline_position -2
modify_font underline_thickness 150%
modify_font baseline 0

cursor                          #aaaaaa
cursor_text_color               #000000
cursor_shape                    block
cursor_blink_interval           0

window_padding_width            8
confirm_os_window_close         0
placement_strategy              center
enable_audio_bell               no

repaint_delay                   5
input_delay                     0
sync_to_monitor                 yes
linux_display_server            wayland
wayland_enable_ime              no

scrollback_lines                5000

detect_urls                     yes
open_url_with                   default
copy_on_select                  yes

foreground                      #aaaaaa
background                      #000000
selection_foreground            #000000
selection_background            #aaaaaa

color0 #000000
color8 #555555

color1 #aa0000
color9 #ff5555

color2  #00aa00
color10 #55ff55

color3  #aa5500
color11 #ffff55

color4  #0000aa
color12 #5555ff

color5  #aa00aa
color13 #ff55ff

color6  #00aaaa
color14 #55ffff

color7  #aaaaaa
color15 #ffffff
